name = "url"
main = "url.js"
compatibility_date = "2025-11-20"
compatibility_date = "2025-09-03"
workers_dev = false
routes = [
  "url.hxorz.cn/*",
]

[observability]
enabled = true
head_sampling_rate = 1
